# Generated by preen — do not edit manually
# Regenerate with: preen sync

import importlib.metadata

project = "preen"
version = importlib.metadata.version("preen")
author = "Gaurav Sood"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

html_theme = "furo"

# MyST settings
myst_enable_extensions = [
    "colon_fence",
    "deflist",
]

# Intersphinx
intersphinx_mapping = {{
    "python": ("https://docs.python.org/3", None),
}}

# Napoleon settings (Google style)
napoleon_google_docstring = True
napoleon_numpy_docstring = False
